import { Typography } from "antd";
import type { NextPage } from "next";
import Head from "next/head";
import Form from "../components/Form";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home-Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          backgroundColor: "#fafafa",
          minHeight: "99vh",
          paddingTop: "4rem",
        }}
      >
        <Form />
      </main>
    </>
  );
};

export default Home;
