import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Form from "../components/Form";
import TableView from "../components/Table";
import { CompanyDetails } from "../typing";

const Home: NextPage = () => {
  const [companyData, setCompanyData] = useState<CompanyDetails[] | []>([]);
  const [addData, setAddData] = useState(true);
  console.log("companyData", companyData);

  return (
    <>
      <Head>
        <title>Home-Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          backgroundColor: "#fafafa",
          minHeight: "99vh",
          paddingTop: "4rem",
        }}
      >
        {!addData ? (
          <TableView />
        ) : (
          <Form
            setCompanyData={setCompanyData}
            companyData={companyData}
            setAddData={setAddData}
          />
        )}
      </main>
    </>
  );
};

export default Home;
